loan_data <-
  read.csv(file = "C:/Users/Ram/Downloads/loans-3.csv", header=TRUE)
colnames(loan_data)[11] <- "cibil"
str(loan_data)
head(loan_data)
library(DataExplorer)
plot_intro(loan_data)
plot_missing(loan_data)
plot_bar(loan_data[,-c(2,7,8)])
plot_bar(loan_data[,"province"])
library(stringr)
loan_data[,"province"] <- str_to_title(loan_data[,"province"])
plot_bar(loan_data[,"province"])
par(mfrow=c(2,2))
barplot(table(loan_data$paid_status, loan_data$gender), col = c("Blue","Red"))
legend("topleft", c("Paid","Pending"), fill = c("Blue","Red"))
barplot(table(loan_data$paid_status, loan_data$education), col = c("Blue","Red"))
legend("topleft", c("Paid","Pending"), fill = c("Blue","Red"))
barplot(table(loan_data$paid_status, loan_data$married_status), col = c("Blue","Red"))
legend("topleft", c("Paid","Pending"), fill = c("Blue","Red"))
barplot(table(loan_data$paid_status, loan_data$agerange), col = c("Blue","Red"))
legend("topleft", c("Paid","Pending"), fill = c("Blue","Red"))
plot_histogram(loan_data)
plot_boxplot(loan_data, by="status")
plot_correlation(na.omit(loan_data), type = "c")
set.seed(567)
library(caTools)
loansample <- sample.split(Y = loan_data$status, SplitRatio = 0.8)
train_data <- loan_data[loansample,]
test_data <- loan_data[!loansample,]
options(warn=-1)
options(scipen=999)

log_model <- glm(status ~ gender+married_status+salary+cibil+appcount+phonegrade+simstrength, family = "binomial", data = train_data)
summary(log_model)
options(warn=-1)
options(scipen=999)

predict <- predict(log_model, test_data, type = 'response')

log_model1 <- glm(status ~ salary+cibil, family = "binomial", data = train_data)
summary(log_model1)
predict <- predict(log_model1, test_data, type = 'response')
pred <- factor(ifelse(predict > 0.1,"1","0"), levels = c("0", "1")) # taking 0.1 as the threshold
cf <- table(test_data$status, pred)
rownames(cf) <- c("Paid","Pending")
colnames(cf) <- c("Predicted non default","Predicted default")
cf
(cf["Paid",1] + cf["Pending",2]) / sum(cf)
cf["Pending",2] / (cf["Pending",2] + cf["Pending",1])
library(ROCR)
ROCRpred <- prediction(predict, test_data$status)
ROCRperf <- performance(ROCRpred, 'tpr','fpr')
plot(ROCRperf, colorize = TRUE, text.adj = c(-0.2,1.7))
library(pROC)
auc(roc(test_data$status, as.numeric(as.character(pred))))
